name: Android Automation Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest --alluredir=allure-results

    - name: Generate Allure Report
      run: |
        pip install allure-pytest
        sudo apt-get install -y default-jre
        wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -zxvf allure-2.27.0.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure
        allure generate allure-results -o allure-report --clean

    - name: Upload Allure Report as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report

    - name: Zip Allure Report
      run: |
        zip -r allure-report.zip allure-report

    - name: Send Report via Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: your-email@gmail.com
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Allure Report - Automated Test Run
        body: "Please find attached the latest test report."
        to: client@example.com, tester@example.com
        from: Appium Test Bot <your-email@gmail.com>
        attachments: allure-report.zip
